server:
  port: 9092

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



  datasource:
    url:  jdbc:mysql://localhost:3306/usermanagement_services_client
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
